#!/usr/bin/env node
// Assembles dist/payload/, the folder the Inno Setup installer (SocialDesk.iss) packs:
//
//   dist/payload/
//     node/        portable node.exe + LICENSE (from fetch-node.mjs)
//     app/         .next build output, server.ts, src/, scripts/, configs and a pruned production node_modules
//     launcher/    launch.ps1, stop.ps1, social-desk.ico (generated by lib/icon.mjs)
//     docs/        Manual-Social-Desk.pdf
//     VERSION.txt
//
// Designed to run on the Windows CI runner after `npm ci` and `npm run build` (the production node_modules gets the
// win32-x64 native packages of the machine that runs it). Usage:
//   node packaging/windows/fetch-node.mjs
//   node packaging/windows/build-payload.mjs [--skip-node]
// --skip-node builds everything except node/ (local trial runs on Linux/macOS).
// Env: PAYLOAD_WARN_MB (default 300) and PAYLOAD_MAX_MB (default 450) size limits.
import { spawnSync } from 'node:child_process';
import { cpSync, existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createIco } from './lib/icon.mjs';
import { APP_ENTRIES, isExcludedFromNextBuild, isPrunedFromNodeModules } from './lib/payload-rules.mjs';

const packagingDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(packagingDir, '..', '..');
const distDir = join(repoRoot, 'dist');
const payloadDir = join(distDir, 'payload');
const appDir = join(payloadDir, 'app');
const skipNode = process.argv.includes('--skip-node');
const isCi = process.env.GITHUB_ACTIONS === 'true';
// Characters reserved for the install folder in front of every payload path, e.g.
// "C:\Users\<user name>\AppData\Local\Programs\SocialDesk\" (~60) plus margin, against the classic 260 MAX_PATH.
const INSTALL_PREFIX_BUDGET = 100;
const MAX_PATH = 259;

function log(message) {
  process.stdout.write(`[build-payload] ${message}\n`);
}

function warn(message) {
  process.stdout.write(isCi ? `::warning title=Windows payload::${message}\n` : `[build-payload] WARNING: ${message}\n`);
}

function fail(message) {
  throw new Error(message);
}

function npmCommand() {
  const candidates = [
    process.env.npm_execpath,
    join(dirname(process.execPath), 'node_modules', 'npm', 'bin', 'npm-cli.js'), // Windows layout
    join(dirname(process.execPath), '..', 'lib', 'node_modules', 'npm', 'bin', 'npm-cli.js'), // Unix layout
  ].filter((candidate) => candidate && candidate.endsWith('.js') && existsSync(candidate));
  // Running npm-cli.js with this same node avoids spawning npm.cmd (Node refuses .cmd files without a shell).
  if (candidates[0]) return { command: process.execPath, prefix: [candidates[0]], shell: false };
  return { command: 'npm', prefix: [], shell: true };
}

function run(args, cwd) {
  const npm = npmCommand();
  log(`$ npm ${args.join(' ')}  (in ${relative(repoRoot, cwd) || '.'})`);
  const result = spawnSync(npm.command, [...npm.prefix, ...args], {
    cwd, stdio: 'inherit', shell: npm.shell,
    env: { ...process.env, npm_config_fund: 'false', npm_config_audit: 'false', npm_config_update_notifier: 'false' },
  });
  if (result.error) fail(`npm ${args[0]} could not start: ${result.error.message}`);
  if (result.status !== 0) fail(`npm ${args[0]} failed with exit code ${result.status}`);
}

/** Total bytes, file count and longest relative path of a directory tree (symbolic links are not followed). */
function measure(root) {
  let bytes = 0;
  let files = 0;
  let longest = '';
  const stack = [root];
  while (stack.length > 0) {
    const current = stack.pop();
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const path = join(current, entry.name);
      const rel = relative(payloadDir, path);
      if (rel.length > longest.length) longest = rel;
      if (entry.isDirectory()) stack.push(path);
      else {
        bytes += lstatSync(path).size;
        files++;
      }
    }
  }
  return { bytes, files, longest };
}

/** Removes pruned entries from node_modules; returns the bytes removed. */
function pruneNodeModules(nodeModules) {
  let removedBytes = 0;
  let removedEntries = 0;
  const stack = [nodeModules];
  while (stack.length > 0) {
    const current = stack.pop();
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const path = join(current, entry.name);
      const rel = relative(nodeModules, path);
      if (isPrunedFromNodeModules(rel)) {
        removedBytes += entry.isDirectory() ? measure(path).bytes : lstatSync(path).size;
        removedEntries++;
        rmSync(path, { recursive: true, force: true });
      } else if (entry.isDirectory() && !entry.isSymbolicLink()) {
        stack.push(path);
      }
    }
  }
  return { removedBytes, removedEntries };
}

const mb = (bytes) => `${(bytes / 1048576).toFixed(1)} MB`;

function main() {
  const manifest = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'));
  log(`Social Desk ${manifest.version} on ${process.platform}-${process.arch}, node ${process.version}`);
  if (process.platform !== 'win32') {
    warn('not running on Windows: native packages in node_modules will NOT match win32-x64 (trial build only)');
  }

  // Preconditions with actionable messages.
  if (!existsSync(join(repoRoot, '.next', 'BUILD_ID'))) fail('.next/BUILD_ID not found: run `npm run build` first');
  if (existsSync(join(repoRoot, 'next.config.ts'))) fail('next.config.ts found: the payload has no SWC binary, use next.config.mjs');
  const manualPdf = join(repoRoot, 'docs', 'manual', 'Manual-Social-Desk.pdf');
  if (!existsSync(manualPdf)) fail('docs/manual/Manual-Social-Desk.pdf not found');
  const nodeSource = join(distDir, 'node-win-x64');
  if (!skipNode && !existsSync(join(nodeSource, 'node.exe'))) {
    fail('dist/node-win-x64/node.exe not found: run `node packaging/windows/fetch-node.mjs` first (or pass --skip-node)');
  }

  rmSync(payloadDir, { recursive: true, force: true });
  mkdirSync(appDir, { recursive: true });

  // 1. Portable runtime.
  if (skipNode) warn('--skip-node: payload has no node/ folder and cannot be installed');
  else cpSync(nodeSource, join(payloadDir, 'node'), { recursive: true });

  // 2. Application files.
  const nextDir = join(repoRoot, '.next');
  for (const entry of APP_ENTRIES) {
    const source = join(repoRoot, entry);
    if (!existsSync(source)) fail(`${entry} not found in the repository`);
    cpSync(source, join(appDir, entry), {
      recursive: true,
      filter: (path) => entry !== '.next' || path === nextDir || !isExcludedFromNextBuild(relative(nextDir, path)),
    });
  }

  // 3. Production dependencies (tsx is a runtime dependency: scripts/start.mjs loads server.ts through it).
  run(['ci', '--omit=dev', '--no-audit', '--no-fund'], appDir);
  const nodeModules = join(appDir, 'node_modules');
  for (const required of ['next', 'react', 'react-dom', 'tsx', 'esbuild']) {
    if (!existsSync(join(nodeModules, required, 'package.json'))) fail(`production node_modules is missing ${required}`);
  }
  if (existsSync(join(nodeModules, 'typescript'))) fail('typescript was installed: dev dependencies leaked into the payload');
  const pruned = pruneNodeModules(nodeModules);
  log(`pruned ${pruned.removedEntries} node_modules entries (${mb(pruned.removedBytes)})`);

  // 4. Launcher (+ generated icon), manual and version stamp.
  cpSync(join(packagingDir, 'launcher'), join(payloadDir, 'launcher'), { recursive: true });
  writeFileSync(join(payloadDir, 'launcher', 'social-desk.ico'), createIco([16, 24, 32, 48, 64, 128, 256]));
  mkdirSync(join(payloadDir, 'docs'), { recursive: true });
  cpSync(manualPdf, join(payloadDir, 'docs', 'Manual-Social-Desk.pdf'));
  const nodeVersion = skipNode ? '(none)' : readFileSync(join(nodeSource, 'NODE_VERSION.txt'), 'utf8').trim();
  const commit = process.env.GITHUB_SHA
    ?? spawnSync('git', ['rev-parse', 'HEAD'], { cwd: repoRoot, encoding: 'utf8' }).stdout?.trim() ?? 'unknown';
  writeFileSync(join(payloadDir, 'VERSION.txt'), [
    `Social Desk ${manifest.version}`,
    `commit: ${commit || 'unknown'}`,
    `node: ${nodeVersion}`,
    `built: ${new Date().toISOString()}`,
    '',
  ].join('\r\n'));

  // 5. Report.
  const parts = {};
  for (const part of ['node', 'app', join('app', 'node_modules'), join('app', '.next'), 'launcher', 'docs']) {
    const path = join(payloadDir, part);
    if (existsSync(path)) parts[part.replaceAll('\\', '/')] = measure(path).bytes;
  }
  const total = measure(payloadDir);
  const report = {
    version: manifest.version, nodeVersion, commit, totalBytes: total.bytes, files: total.files,
    longestPath: total.longest, longestPathLength: total.longest.length, parts,
  };
  writeFileSync(join(distDir, 'payload-report.json'), `${JSON.stringify(report, null, 2)}\n`);
  log('payload size by part:');
  for (const [part, bytes] of Object.entries(parts)) log(`  ${part.padEnd(18)} ${mb(bytes)}`);
  log(`TOTAL ${mb(total.bytes)} in ${total.files} files`);
  log(`longest path (${total.longest.length} chars): ${total.longest}`);

  const warnMb = Number(process.env.PAYLOAD_WARN_MB ?? 300);
  const maxMb = Number(process.env.PAYLOAD_MAX_MB ?? 450);
  if (total.bytes > maxMb * 1048576) fail(`payload is ${mb(total.bytes)}, above PAYLOAD_MAX_MB=${maxMb}`);
  if (total.bytes > warnMb * 1048576) warn(`payload is ${mb(total.bytes)}, above the ${warnMb} MB target`);
  if (total.longest.length + INSTALL_PREFIX_BUDGET > MAX_PATH) {
    warn(`longest payload path is ${total.longest.length} chars; with a long install folder it may exceed MAX_PATH (${MAX_PATH})`);
  }
  log(`done: ${payloadDir}`);
}

try {
  main();
} catch (error) {
  process.stderr.write(`[build-payload] ERROR: ${error.message}\n`);
  if (isCi) process.stdout.write(`::error title=Windows payload::${error.message}\n`);
  process.exit(1);
}
